#-------------------------------
# General Site Settings

title: Amelia Carlson
description: TODO write something # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "blog.ascarlson.art" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Amelia Carlson
author-avatar: author.jpg


#-------------------------------
# Contact links
instagram: https://www.instagram.com/as_carlson/
linkedin: https://www.linkedin.com/in/amelia-carlson-535471174/


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
